# Generated by Django 4.1.2 on 2022-11-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_relationship_studysessionmodel_profile_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysessionmodel',
            name='text',
            field=models.TextField(),
        ),
    ]
